### ISSUE TITLE
Interop with reactive in other languages?

### ISSUE THREAD

**Issue by ivnsch** [aepsil0n/carboxyl#108]
I was wondering, how feasible it is to use this library in a custom business logic library (written in Rust), which is meant to be used in an interface-specific environment - say an iOS Swift app, which also use reactive (e.g. rxswift)?

The idea would be that the business logic library exposes observables (and other things) which can be somehow observed / composed in the apps.

\* I'm a Rust newbie -  I know this is a very broad (and maybe difficult) answer, just want to get an idea of the possibilities even if it's very vague.

**Comment by milibopp** [comment]
Before I comment, a quick disclaimer: I don't know Swift, the iOS ecosystem or RxSwift for that matter. So any comment can only be very general.

That being said, it is absolutely possible to interface different reactive systems with each other. However, the most realistic way is probably to treat them like separate services. That does not necessarily mean, that they have to run in different processes and communicate over network. But they should have a means to pass messages to each other – through multi-threaded channels, local network, pipes or whatever you do on iOS for this.

In any case, I would strongly recommend against trying to make carboxyl streams act as Rx observables though. While it may theoretically be possible, there are semantic subtleties between different FRP systems that could be very hard to sensibly translate between the systems. Also, independent of whether it is possible, it generally makes sense to separate software components like that at the service-level, rather than an library-APi level.

My assumption for your case would be, that you want to use RxSwift for UI, whereas the Rust/carboxyl part would operate purely on the domain model that needs to keep some internal state. I assume you have good reasons for not using a database for that. If you had a database, FRP would be overkill, you should probably just use a stateless microservice instead to implement the business logic.

Also I never tested this library on a phone. I don't see why it would not work, but there may be caveats that you only find through testing. Please let me know how it turns out, if you do decide to use carboxyl.

**Comment by milibopp** [comment]
As this was mostly a question, I am going to close the issue. Feel free to reopen, if anything is unclear or make a new issue if you run into more specific problems or have other questions.

**Comment by ivnsch** [comment]
Thanks for your answer @aepsil0n! I haven't had time to continue digging into this.
